version: '3'

services:
  app:
    build: .
    volumes:
      - .:/djangoProjectFinalVersion
    ports:
      - "8000:8000"
    image: app:djangoProjectFinalVersion
    container_name: blog_container
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
  db:
    image: mongo
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: root
        MONGO_INITDB_DATABASE: django
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
      - ./data-db:/data/db
      - ./media/images:/media/images
    ports:
      - "27017:27017"
    container_name: mongodb_container